#!/bin/bash
mkdir -p $(pwd)/docs

DOXYFILE=$(pwd)/docs/Doxyfile

rm $DOXYFILE
# generating default Doxyfile
doxygen -g $DOXYFILE

PROJ_DIR=$(pwd)/
OUTPUT_DIR=$(pwd)/docs/documentation
echo $OUTPUT_DIR

PROJECT_NAME="TestProjectNam11e"
PROJECT_NUMBER="1.0.0"
PROJECT_BRIEF="Brief description of project"
PROJECT_LOGO=""
OUTPUT_DIRECTORY="$OUTPUT_DIR"
INPUT="$PROJ_DIR"
CREATE_SUBDIRS="NO"
ALLOW_UNICODE_NAMES="NO"
OUTPUT_LANGUAGE="English"
OUTPUT_TEXT_DIRECTION="None"
BRIEF_MEMBER_DESC="YES"
REPEAT_BRIEF="YES"
RECURSIVE="YES"
GENERATE_HTML="YES"
GENERATE_LATEX="NO"
USE_MDFILE_AS_MAINPAGE="README.md"

# Change default values in Doxyfile
sed -i "s/^PROJECT_NAME *=.*/PROJECT_NAME = $PROJECT_NAME/" "$DOXYFILE"
sed -i "s|^PROJECT_NUMBER *=.*|PROJECT_NUMBER = $PROJECT_NUMBER|" "$DOXYFILE"
sed -i "s|^PROJECT_BRIEF *=.*|PROJECT_BRIEF = $PROJECT_BRIEF|" "$DOXYFILE"
# sed -i "s|^PROJECT_LOGO *=.*|PROJECT_LOGO = $PROJECT_LOGO|" "$DOXYFILE"
sed -i "s|^OUTPUT_DIRECTORY *=.*|OUTPUT_DIRECTORY = $OUTPUT_DIRECTORY|" "$DOXYFILE"
sed -i "s|^INPUT *=.*|INPUT = $INPUT README.md|" "$DOXYFILE"
# sed -i "s|^CREATE_SUBDIRS *=.*|CREATE_SUBDIRS = $CREATE_SUBDIRS|" "$DOXYFILE"
# sed -i "s|^ALLOW_UNICODE_NAMES *=.*|ALLOW_UNICODE_NAMES = $ALLOW_UNICODE_NAMES|" "$DOXYFILE"
# sed -i "s|^OUTPUT_LANGUAGE *=.*|OUTPUT_LANGUAGE = $OUTPUT_LANGUAGE|" "$DOXYFILE"
# sed -i "s|^OUTPUT_TEXT_DIRECTION *=.*|OUTPUT_TEXT_DIRECTION = $OUTPUT_TEXT_DIRECTION|" "$DOXYFILE"
# sed -i "s|^BRIEF_MEMBER_DESC *=.*|BRIEF_MEMBER_DESC = $BRIEF_MEMBER_DESC|" "$DOXYFILE"
# sed -i "s|^REPEAT_BRIEF *=.*|REPEAT_BRIEF = $REPEAT_BRIEF|" "$DOXYFILE"
sed -i "s|^RECURSIVE *=.*|RECURSIVE = $RECURSIVE|" "$DOXYFILE"
sed -i "s/^GENERATE_HTML *=.*/GENERATE_HTML = $GENERATE_HTML/" "$DOXYFILE"
sed -i "s/^GENERATE_LATEX *=.*/GENERATE_LATEX = $GENERATE_LATEX/" "$DOXYFILE"
sed -i "s/^USE_MDFILE_AS_MAINPAGE *=.*/USE_MDFILE_AS_MAINPAGE = $USE_MDFILE_AS_MAINPAGE/" "$DOXYFILE"

# generate docs
rm $OUTPUT_DIR
doxygen $DOXYFILE