name: Build & Test
on:
  push:
    branches: [ "master", "release/*", feature/* ]
  pull_request:
   branches: ["master"]
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
      
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Build
        run: scripts/build.sh --arch=x86_64 --docker --build-type=Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            install/

  tests:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts/

      - name: Run Tests
        run: |
          mkdir /tmp/test_results
          find "artifacts/tests/" -type f -exec chmod +x {} \; -exec {} --gtest_output=xml:/tmp/test_results/xunit.xml \;

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            /tmp/test_results/*.xml






    
    
        