name: Build & Test
on:
  push:
    branches: [ "master", "release/*", feature/* ]
  pull_request:
   branches: ["master"]
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
      
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Build
        run: scripts/build.sh --arch=x86_64 --docker --build-type=Release --build-targets=Apps

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts/

  tests:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      # - name: Install Software
      #   run: apt-get install -y lcov
      #   shell: bash

      - name: Clone Project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # - name: Download Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: artifacts
      #     path: artifacts/

      - name: Run Build
        run: scripts/build.sh --arch=x86_64 --docker --build-type=Release --build-targets=Tests

      - name: Run Tests
        run: scripts/run_all_tests.sh artifacts

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: |
            artifacts/test_report

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action/linux@v2
      #   if: always()
      #   with:
      #     files: |
      #       /tmp/test_results/*.xml






    
    
        