name: Project Documentation
on:
  push:
    branches: [ "master", "release/*", feature/* ]
  pull_request:
   branches: ["master"]
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
      
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Build
        run: scripts/build.sh --arch=x86_64 --docker --build-type=Release

      - name: Collecting All Artifacts
        run: mkdir artifacts && cp -r ./install artifacts/install && cp -r ./scripts artifacts/scripts


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts

  tests:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./artifacts

      - name: Run Tests
        run: |
          ./artifacts/scripts/run_all_tests.sh
        shell: bash






    
    
        