name: Project Documentation
on:
  push:
    branches: [ "master", "release/*", feature/* ]
  pull_request:
   branches: ["master"]
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
      
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Build
        run: scripts/build.sh --arch=x86_64 --docker --build-type=Release

  tests:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Check Installed Software
        run: |
          scripts/run_all_tests.sh
        shell: bash






    
    
        