name: Project Documentation
on:
  push:
    branches:
      - feature/docs
      - master
  pull_request:
   branches:
   - main

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
        
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen doxygen-doc
        shell: bash

      - name: Run Doxygen
        run: scripts/config_doxygen.sh

      - name: Upload Docs
        #id: deployment
        uses: actions/upload-pages-artifact@v3 
        with:
          path: documentation/html

      - name: Setup Pages
        run: echo " ============ Setup Pages ============"
        
      - name: Deploy To Gihub Pages
        run: echo " ============ Deploy To Gihub Pages ============"
