name: Project Documentation
on:
  push:
    branches:
      - feature/docs
      - master
  pull_request:
   branches:
   - main

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Installed Software
        run: whereis git && whereis python && whereis pip
        shell: bash
        
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Doxygen
        run: apt update && apt -y upgrade && apt install -y --no-install-recommends doxygen doxygen-doc
        shell: bash

      - name: Run Doxygen
        run: echo " ============ Run Doxygen ============"

      - name: Upload Docs
        run: echo " ============ Upload Docs ============"

      - name: Setup Pages
        run: echo " ============ Setup Pages ============"
        
      - name: Deploy To Gihub Pages
        run: echo " ============ Deploy To Gihub Pages ============"
